name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: 'src'
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: 'src'
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: 'src'

    - name: Code coverage summary to console
      uses: irongut/CodeCoverageSummary@v1.0.1
      with:
        filename: '**/coverage.cobertura.xml'
        badge: true

    - name: Code coverage summary to HTML
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.8
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'coveragereport' 
        reporttypes: 'HtmlInline;Cobertura' # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary
        verbosity: 'Info' 
        tag: '${{ github.run_number }}_${{ github.run_id }}'

    - name: Upload HTML coverage report artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: CoverageReport       
        path: coveragereport
