name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: 'src'
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: 'src'
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: 'src'

    -name: Install Report generator
     run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Test
      run: reportgenerator "-reports:src\PaymentGateway.UnitTests\TestResults\9a3cf61c-3c41-4b3f-a9a5-61bffee792dd\coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html
